"""empty message

Revision ID: 0db20c24b3a8
Revises: 1c7cad78e475
Create Date: 2016-09-06 00:26:47.537563

"""

# revision identifiers, used by Alembic.
revision = '0db20c24b3a8'
down_revision = '1c7cad78e475'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_user')
    ### end Alembic commands ###
