"""empty message

Revision ID: 1b3ee51597eb
Revises: 86756508e55d
Create Date: 2016-08-29 13:30:25.116076

"""

# revision identifiers, used by Alembic.
revision = '1b3ee51597eb'
down_revision = '86756508e55d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('area', sa.String(length=128), nullable=True))
    op.add_column('request', sa.Column('client', sa.String(length=128), nullable=True))
    op.add_column('request', sa.Column('date', sa.String(length=128), nullable=True))
    op.add_column('request', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('request', sa.Column('priority', sa.String(length=128), nullable=True))
    op.add_column('request', sa.Column('url', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'url')
    op.drop_column('request', 'priority')
    op.drop_column('request', 'description')
    op.drop_column('request', 'date')
    op.drop_column('request', 'client')
    op.drop_column('request', 'area')
    ### end Alembic commands ###
