"""empty message

Revision ID: 287d2a78dcba
Revises: None
Create Date: 2016-09-02 17:32:33.788479

"""

# revision identifiers, used by Alembic.
revision = '287d2a78dcba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('client', sa.String(length=8), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature')
    ### end Alembic commands ###
