"""empty message

Revision ID: 4bd2f1af2761
Revises: 7cf3144b71ef
Create Date: 2016-09-03 23:36:37.696332

"""

# revision identifiers, used by Alembic.
revision = '4bd2f1af2761'
down_revision = '7cf3144b71ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
