"""empty message

Revision ID: 71031560dd44
Revises: None
Create Date: 2016-08-29 19:30:18.546708

"""

# revision identifiers, used by Alembic.
revision = '71031560dd44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('client', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=128), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature')
    ### end Alembic commands ###
