"""empty message

Revision ID: 792144c470e2
Revises: f6a7df720ce7
Create Date: 2016-09-07 02:07:19.343790

"""

# revision identifiers, used by Alembic.
revision = '792144c470e2'
down_revision = 'f6a7df720ce7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_user', 'authenticated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_user', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
