"""empty message

Revision ID: 7cf3144b71ef
Revises: 670798bb3c53
Create Date: 2016-09-03 23:35:46.922883

"""

# revision identifiers, used by Alembic.
revision = '7cf3144b71ef'
down_revision = '670798bb3c53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey')
    )
    ### end Alembic commands ###
