"""empty message

Revision ID: 86756508e55d
Revises: None
Create Date: 2016-08-28 23:05:20.339625

"""

# revision identifiers, used by Alembic.
revision = '86756508e55d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    ### end Alembic commands ###
