"""empty message

Revision ID: 9ab58feefea6
Revises: 792144c470e2
Create Date: 2016-09-07 02:45:00.317493

"""

# revision identifiers, used by Alembic.
revision = '9ab58feefea6'
down_revision = '792144c470e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_user')
    ### end Alembic commands ###
