"""empty message

Revision ID: f6a7df720ce7
Revises: 0db20c24b3a8
Create Date: 2016-09-06 22:35:04.402522

"""

# revision identifiers, used by Alembic.
revision = 'f6a7df720ce7'
down_revision = '0db20c24b3a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_user', 'authenticated')
    ### end Alembic commands ###
